import type { NextPage } from "next";
import { useTheme } from "next-themes";
import Head from "next/head";
import { useEffect, useState } from "react";
import ProjectPage from "../components/Projects/projects";

const Projects: NextPage = () => {
  const [mounted, setMounted] = useState(false);
  // useEffect only runs on the client, so now we can safely show the UI
  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return null;
  }
  return (
    <div>
      <Head>
        <title>Projects - Tomo Takebuchi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProjectPage />
      </main>
    </div>
  );
};

export default Projects;
